version: "3.8"

# hydor has 2 quad core Intel Xeon E5-2637, 16 threads in total, with 64GB of RAM

services:
  # 8GB of VRAM
  gtx1080:
    build:
      context: ../image
      args:
        base: nvidia/cuda:11.0-cudnn8-devel-ubuntu18.04
    runtime: nvidia
    environment:
      NVIDIA_DRIVER_CAPABILITIES: "compute,utility"
      NVIDIA_VISIBLE_DEVICES: "GPU-748e7ab6-e7a6-caaa-5c75-398395a2c80d"
      JULIA_NUM_THREADS: 3
    env_file: ../token.env
    restart: unless-stopped
    command:
      - start
      - --disconnect-after-job
      - --tags=queue=juliagpu,cuda=10.0,cuda=10.1,cuda=10.2,cuda=11.0,cuda=9.0,cuda=9.2,cap=sm_61
      - --name=gtx1080.hydor.elis.ugent.be
    volumes:
      - /storage/buildkite/gtx1080:/root

  # 11GB of VRAM
  rtx2080:
    build:
      context: ../image
      args:
        base: nvidia/cuda:11.0-cudnn8-devel-ubuntu18.04
    runtime: nvidia
    environment:
      NVIDIA_DRIVER_CAPABILITIES: "compute,utility"
      NVIDIA_VISIBLE_DEVICES: "GPU-fa79b18d-3e09-142a-2493-bb83b07b0bdf"
      JULIA_NUM_THREADS: 4
    env_file: ../token.env
    restart: unless-stopped
    command:
      - start
      - --disconnect-after-job
      - --tags=queue=juliagpu,cuda=10.0,cuda=10.1,cuda=10.2,cuda=11.0,cuda=9.0,cuda=9.2,cap=sm_75,latest
      - --name=rtx2080.hydor.elis.ugent.be
    volumes:
      - /storage/buildkite/rtx2080:/root

